name: Test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - ci

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test library on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            cmake_args: "-DCMAKE_LINKER_TYPE=MOLD -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15"
            nparallel: 4
          - name: Windows-x64
            os: windows-2022
            cmake_args: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
            nparallel: 4
          - name: Windows-ARM64
            os: windows-2022
            cmake_args: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_FLAGS="--target=arm64-pc-windows-msvc" -DCMAKE_CXX_FLAGS="--target=arm64-pc-windows-msvc"
            nparallel: 4
          # TODO: enable this when LLVM 20 is available (https://github.com/llvm/llvm-project/issues/113658)
          # - name: Windows-ARM64EC
          #   os: windows-2022
          #   cmake_args: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_FLAGS="/arm64EC" -DCMAKE_CXX_FLAGS="/arm64EC" -DCMAKE_EXE_LINKER_FLAGS="/MACHINE:ARM64EC" -DCMAKE_SHARED_LINKER_FLAGS="/MACHINE:ARM64EC" -DCMAKE_STATIC_LINKER_FLAGS="/MACHINE:ARM64EC"
          #   nparallel: 4
          - name: MacOS
            os: macos-14
            cmake_args: "-D\"CMAKE_OSX_ARCHITECTURES=arm64;x86_64\""
            nparallel: 4

    steps:
      - name: Install Linux Deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev libjack-jackd2-dev
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
          sudo apt install clang-15 -y

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - uses: rui314/setup-mold@v1
        if: runner.os == 'Linux'

      - name: Upgrade LLVM
        if: runner.os == 'Windows'
        run: choco upgrade llvm --version=18.1.8 --allow-downgrade

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2

      - name: Setup MSVC devcmd (x64)
        if: matrix.name == 'Windows-x64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup MSVC devcmd (arm64)
        if: matrix.name == 'Windows-ARM64' || matrix.name == 'Windows-ARM64EC'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64_arm64

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cmake Configure
        run: cmake -Bbuild -G"Ninja Multi-Config" -DCHOWDSP_FFT_TESTING=ON ${{ matrix.cmake_args }}

      - name: Build Test C++ (Debug)
        run: cmake --build build --config Debug --parallel ${{ matrix.nparallel }} --target test_chowdsp_fft_cpp

      - name: Run Test C++ (Debug)
        if: ! (matrix.name == 'Windows-ARM64' || matrix.name == 'Windows-ARM64EC')
        run: ./build/test/Debug/test_chowdsp_fft_cpp

      - name: Build Test C (Debug)
        run: cmake --build build --config Debug --parallel ${{ matrix.nparallel }} --target test_chowdsp_fft_c

      - name: Run Test C (Debug)
        if: ! (matrix.name == 'Windows-ARM64' || matrix.name == 'Windows-ARM64EC')
        run: ./build/test/Debug/test_chowdsp_fft_c

      - name: Build Test C++ (Release)
        run: cmake --build build --config Release --parallel ${{ matrix.nparallel }} --target test_chowdsp_fft_cpp

      - name: Run Test C++ (Release)
        if: ! (matrix.name == 'Windows-ARM64' || matrix.name == 'Windows-ARM64EC')
        run: ./build/test/Release/test_chowdsp_fft_cpp
